FROM n8nio/n8n:latest

USER root
RUN apk add --update python3 py3-pip libxml2-dev libxslt-dev

USER node
RUN python3 -m pip install --user --break-system-packages pipx
RUN python3 -m pip install --user --break-system-packages grobid-client-python

ENV PATH="/home/node/.local/bin:${PATH}"