FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY client_qdrant_flask_docker.py .

EXPOSE 5000

CMD ["python", "client_qdrant_flask_docker.py"] 